### ISSUE TITLE
Set up Github Pages

### ISSUE THREAD

**Issue by webdev03** [SpellCheckJS/html-client#7]
why not?

**Comment by hello-smile6** [comment]
Good idea.

**Comment by hello-smile6** [comment]
> why not?

Could you help set it up?

**Comment by imdevarsh** [comment]
I can't.
@hello-smile6 Stop marking my things offtopic

**Comment by imdevarsh** [comment]
Just turn it on, in the settings.

**Comment by hello-smile6** [comment]
> Just turn it on, in the settings.

Okay

**Comment by hello-smile6** [comment]
Done. https://spellcheckjs.github.io/html-client/
